### ISSUE TITLE
Plugin wont enable on Octoprint 1.9.3

### ISSUE THREAD

**Issue by artandtechvof** [jcassel/OctoPrint-Siocontrol#12]
Plugin wont enable on Octoprint 1.9.3
SIO-control reports Python requirement >=2.7, **<3**
After enabling and restarting octoprint plugin is disabled, based on incorrect Python version? Should be **<4** ?
Tried installing via plugin manager and directly using the URL, same result.

No sidebar is added to the Octoprint UI.

**Comment by jcassel** [comment]
Not sure how that could be getting reported. The Plugin has never required anything less than 3.  If you look right now in the code, it says. 

On line (43) of setup.py:
`additional_setup_parameters = {"python_requires": ">=3,<4"}`

And on line (559) of __init__.py:
`__plugin_pythoncompat__ = ">=3,<4"  # Only Python 3`

And it has always been that way.

**Comment by jcassel** [comment]
@artandtechvof 
I have SIOC installed on many systems running 3.10.12. 

If you still feel strongly that this message is related to the SIO Control, please supply your SystemInfo Bundle. At the very least the log file where you got the message would be very helpful.

**Comment by artandtechvof** [comment]
The setup.py is correct, but after installing SIO control list something else in the Installed Plugings
I will keep investigating why this is.
I ma running OctoPrint 1.9.3 Python 3.7.3 OctoPi 0.18.0

![image](https://github.com/jcassel/OctoPrint-Siocontrol/assets/42702299/7e778735-4507-406b-b319-2661c49f36c8)

**Comment by artandtechvof** [comment]
System info bundle;

[octoprint-systeminfo-20240103092719.zip](https://github.com/jcassel/OctoPrint-Siocontrol/files/13817438/octoprint-systeminfo-20240103092719.zip)

**Comment by jcassel** [comment]
Looking at the log, I see this... 
"WARNING - Plugin SIO-Control (0.6.5) can't be compiled under Python 3.7.3 due to invalid syntax"

This seems to indicate that Python 3.7.3 thinks there is an issue with the SIOC Code when it is trying to compile it.  It does not give a lot of details on what the syntax issue is but there is a bit more there.
This bit is intresting: 
```
File "<fstring>", line 1
    (pin=)"

```
I don't have a dev system with 3.7.3 on it. I will see if I can set that up and find out what its issue is.  However it does indicate that it is an issue related to a string format that uses "pin=" in it.  I only have one place that exists. There are several ways to do what I am doing in that line of code. I updated the code to do it differently.  I also tested it on one of my systems with 3.10.12 but it already worked there.

Can you grab this version and test that it works for you now? If you report that it corrects your issue, I will merge the change in and make a release. 

You can download the zip here;
[version 0.6.6 test](https://codeload.github.com/jcassel/OctoPrint-Siocontrol/zip/refs/heads/12-plugin-wont-enable-on-octoprint-193)

Or past this into the "From URL" box.
https://codeload.github.com/jcassel/OctoPrint-Siocontrol/zip/refs/heads/12-plugin-wont-enable-on-octoprint-193

Let me know your results.

**Comment by jcassel** [comment]
I setup a test system and confirmed that this solves the issue. Merged in the change, issue closed.
